### DISCUSSION TITLE
Ideas

### DISCUSSION THREAD

**Discussion by Explosion-Scratch** [asmcss/assembler#24] [Ideas]
Hi! I really love this project and I had a few ideas for it:

- Lighten and darken colors? E.g. `lighten(@${0}, 20)` (out of 100)
- Built in color palette (It's sort of annoying to import the material design one every time
- `<x-style>` tag supporting css-like syntax something like this:
```css
/* It'd  be cool to support multiple properties on one line */
mixin:button {
	inline-flex; 
	^reset; 
	^button-color:${0=grey};
	justify-content:center; align-items:center;
	cursor:pointer;
	cursor.disabled:not-allowed;
	py:4; px:6;
	/* Multiple on one line */
	opacity.disabled:50%; transition:all 0.25s;
	border; 
	/* Mostly formatted like CSS */
	color:white; 
	uppercase; 
	radius
}
/* Also supporting normal syntax CSS */
button {
	^button:yellow;
    color: black;
}
```
- A JavaScript API
```js
Assembler.compile(css_code);//Would return the actual CSS generated, not the classes and variables but the actual CSS that would do the identical thing.

Assembler.addMixin("mixin name", "Props and stuff here");

Assembler.addShorthand("bgc", "background-color"); /* Now bgc maps to background-color */
```
